### ISSUE TITLE
Global URL Hashtable on the server

### ISSUE THREAD

**Issue by rajatjain1997** [ContentHolmes/Content-Holmes#51]
A global hashtable for bad urls needs to be on the server. This is entirely optional for now, but this will help us reduce our image check calls. We can put it through a bloom filter in the sense that if the URL might be on the server, we send a request out to check it, otherwise it is not on the server as there are no false negatives.

**Comment by Mrigesh08** [comment]
I am maintaining a json object of all the bad urls communicated by the extension. We can convert it into a hash table but that would be overkill. So let it be this way as of now.
